### PR TITLE
Add MustGet() function for fixed flags

### PR DESCRIPTION
**Pull request by infalmo**

### CODE REVIEW

**Comment by infalmo** [comment]
https://github.com/spf13/pflag/pull/272

**Comment by cornfeedhobo** [comment]
@infixint943 Howdy. Could you do me a favor and merge master or rebase? I've added some more types in this fork. I'll be happy to merge once that's out. Thanks!

**Comment by infalmo** [comment]
Well, I could use some help regarding this.
Since I've made a PR to multiple repos, changes in one are reflected in the other.
So, is making a separate branch per repo and working on that the way to go?
Or is there any other method I should follow?

**Comment by cornfeedhobo** [comment]
Since you forked from his repo, I'll walk you through what I would do...

Create a new remote for this repo
```
git remote add cornfeedhobo https://github.com/cornfeedhobo/pflag
```

Start a rebase
```
git rebase --interactive cornfeedhobo/master
```

Rebase will then attempt to apply your changes on top of all the commits between our common ancestor, and give you a few options to follow. Let me know if you have trouble.

You can always abort with `git rebase --abort`

**Comment by cornfeedhobo** [comment]
@infixint943 If you want to stay agnostic to either of our repos, you can create a dedicated branch to track each master, but you'll run into a nightmare merging into your master. You kind of have to commit to one or the other, but it can be done.

**Comment by infalmo** [comment]
Thanks a lot for the help. Will try it out!

**Comment by cornfeedhobo** [comment]
@infixint943 here are the agnostic instructions. This will allow you to keep both PRs.

Create a new remote for this repo
```
git remote add cornfeedhobo https://github.com/cornfeedhobo/pflag
```

Create a new branch for this remote
```
git checkout -b cornfeedhobo cornfeedhobo/master
```

Create a new branch for this pr
```
git checkout -b cfh-must-get
```

Copy the work you've committed to master
```
git diff master > master.patch
git apply master.patch
rm master.patch
```

Finally, deal with any conflicts, add the needed functions for the additional types, and push your new branch.

**Comment by infalmo** [comment]
Thanks a lot, will have it done when I'm free. A bit caught up in school work currently.
Thanks again!

**Comment by infalmo** [comment]
Okay, I've made the changes with the instructions specified above. There were some persistent issues while applying the patch, so I merged the master branch to the `cfh-must-get` directly. Hopefully there isn't much of an issue with this method.

So, if I'm not wrong, I'll have to close this PR and create a new PR for the new branch created (since I can't change the branch using `Edit` above). If this is right, could I have this done on October 1st (3 days from today) since it would count towards my hacktober PR count? Please?

**Comment by cornfeedhobo** [comment]
@infixint943 Yeah, if you can't change the base branch then you'll need to create a new PR.

> could I have this done on October 1st

Do you mean "on" or "by"? I'm sure I can accommodate either. This change is really straight forward.

**Comment by infalmo** [comment]
https://github.com/cornfeedhobo/pflag/pull/9

**Pull request closed without merging**
