### PR TITLE
UnquoteUsage fixes

### LINKED ISSUE #200: Document behavior of backticks in usage string
Pflag changes the type of a flag to match a string in back quotes in the usage string. For example, if flag "test" had usage message "this sets up the `testtype` variable", the output would be:

```
      --test testtype  this sets up the testtype variable
```

This is unexpected behavior and is also not documented anywhere except in this godoc for the `UnquoteUsage` function: https://godoc.org/github.com/spf13/pflag#UnquoteUsage

This should be documented somewhere more visibly as back quotes are commonly used in descriptions and usage text.

### PR DESCRIPTION
**Pull request by cornfeedhobo**
- copy docs from flag about backticks
- support setting a custom usage type
- support disabling unquoting

fixes spf13/pflag#200

### CODE REVIEW

**Comment by cornfeedhobo** [comment]
@dpopp07 @AlexNPavel I think this addresses your concerns. Let me know what you think.

**Comment by dpopp07** [comment]
@cornfeedhobo I think this looks great, certainly addresses my concerns. Thanks for putting this together so quickly

**Comment by cornfeedhobo** [comment]
@dpopp07 awesome. no problem. I'll write some tests this evening and get this out!

**Comment by cornfeedhobo** [comment]
still working on this, but should be wrapped up soon

**Comment by cornfeedhobo** [comment]
@dpopp07 @AlexNPavel Alright, last ping. I think this satisfies all conditions. Let me know what you think.

**Comment by crazy-max** [comment]
@cornfeedhobo Definitely looks great. Could you open a PR on the upstream repo with these changes? That would be awesome! :pray:

**Comment by cornfeedhobo** [comment]
@crazy-max sorry, I've given up on that. They don't have any interest in good stewardship. You are welcome to start using this repo and ping me on any other upstream feature requests you'd like me to pull in.

**Pull request merged**
